name: slyverin
description: A library of flutter sliver implementations.
version: 0.1.0
homepage: https://github.com/blaugold/slyverin
repository: https://github.com/blaugold/slyverin
issue_tracker: https://github.com/blaugold/slyverin/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
